# PROD

services:

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      LISTEN_ADDRESSES: "*"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blog_db
    volumes:
      - ./blogs-back/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./blogs-back/mongo_data:/data/db

  server:
    image: blogs-back-prod
    hostname:
      server
    build:
      context: './blogs-back' # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./blogs-back/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
      - ./blogs-front/build/:/usr/src/app/build
    ports:
      - 9001:3000
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/blog_db
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo_data:
