version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blog_db
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  server:
    image: blogs-back-dev
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 9001:9001
    #environment:
    #  - MONGO_URL=mongodb://the_username:the_password@mongo:27017/blog_db # This comes from .env
    depends_on:
      - mongo

volumes:
  mongo_data:
  